project:
  type: website
  output-dir: docs

website:
  title: "Lingxuan Gao & Xiaoqing Chen - MUSA 5080 Final Project Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      
      - text: Final Project
        menu:
          - href: "Eviction.qmd"
            text: "Eviction Risk Prediction in Philadelphia"
              
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    css: styles.css
    page-layout: full

execute:
  freeze: auto
